config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  resources :users
  resources :posts
  resources :game_blogs
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game_blog.rb
class GameBlog < ApplicationRecord
  validates_presence_of :name

  has_many :posts
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :body

  belongs_to :game_blog
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :username
  validates_uniqueness_of :username
  EMAIL_FORMAT_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: EMAIL_FORMAT_REGEX }, uniqueness: true

  before_save { self.email = email.downcase if email }
  has_many :game_blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_current_user
    render file: 'public/404', status: 404 unless current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_current_user

  def index

  end
end

app/controllers/game_blogs_controller.rb
class GameBlogsController < ApplicationController
  before_action :set_game_blog, only: %i[ show edit update destroy ]

  # GET /game_blogs or /game_blogs.json
  def index
    @game_blogs = GameBlog.all
  end

  # GET /game_blogs/1 or /game_blogs/1.json
  def show
  end

  # GET /game_blogs/new
  def new
    @game_blog = GameBlog.new
  end

  # GET /game_blogs/1/edit
  def edit
  end

  # POST /game_blogs or /game_blogs.json
  def create
    @game_blog = GameBlog.new(game_blog_params)

    respond_to do |format|
      if @game_blog.save
        format.html { redirect_to @game_blog, notice: "Game blog was successfully created." }
        format.json { render :show, status: :created, location: @game_blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_blogs/1 or /game_blogs/1.json
  def update
    respond_to do |format|
      if @game_blog.update(game_blog_params)
        format.html { redirect_to @game_blog, notice: "Game blog was successfully updated." }
        format.json { render :show, status: :ok, location: @game_blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_blogs/1 or /game_blogs/1.json
  def destroy
    @game_blog.destroy
    respond_to do |format|
      format.html { redirect_to game_blogs_url, notice: "Game blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_blog
      @game_blog = GameBlog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_blog_params
      params.require(:game_blog).permit(:name)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :game_blog_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:danger] = 'That email & password combination do not match. Please try again.'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to dashboard_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_blogs_helper.rb
module GameBlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<section id="user-information">
</section>

<% current_user.game_blogs.each do |blog| %>
  <section id="blog-<%=blog.id%>">
    <h2><%= blog.name %></h2>
    <% blog.posts.each do |post| %>
      <section id="blog-<%=blog.id%>-posts-<%=post.id%>">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
      </section>
      <%= link_to 'Edit Post', edit_post_path(post) %>
    <% end %>
    <%= link_to 'Edit Blog', edit_game_blog_path(blog) %>
  </section>
  <br>
<% end %>

app/views/game_blogs/_form.html.erb
<%= form_with(model: game_blog) do |form| %>
  <% if game_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game_blog.errors.count, "error") %> prohibited this game_blog from being saved:</h2>

      <ul>
        <% game_blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/game_blogs/edit.html.erb
<h1>Editing Game Blog</h1>

<%= render 'form', game_blog: @game_blog %>

<%= link_to 'Show', @game_blog %> |
<%= link_to 'Back', game_blogs_path %>

app/views/game_blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Game Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_blogs.each do |game_blog| %>
      <tr>
        <td><%= game_blog.name %></td>
        <td><%= link_to 'Show', game_blog %></td>
        <td><%= link_to 'Edit', edit_game_blog_path(game_blog) %></td>
        <td><%= link_to 'Destroy', game_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Blog', new_game_blog_path %>

app/views/game_blogs/new.html.erb
<h1>New Game Blog</h1>

<%= render 'form', game_blog: @game_blog %>

<%= link_to 'Back', game_blogs_path %>

app/views/game_blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game_blog.name %>
</p>

<%= link_to 'Edit', edit_game_blog_path(@game_blog) %> |
<%= link_to 'Back', game_blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostGameLobby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if current_user %>
        Hi <%= current_user.username %>
        |
        <%= link_to 'Log out', logout_path, method: :delete %>
      <% else %>
        <%= link_to 'Log in', login_path %>
        |
        <%= link_to 'Sign up', new_user_path %>
      <% end %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Haldo</h1>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :game_blog_id %>
    <%= form.text_field :game_blog_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Game blog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.game_blog_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Game blog:</strong>
  <%= @post.game_blog_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.label :username %>
    <%= form.text_field :username %>

    <%= form.label :email %>
    <%= form.text_field :email %>

    <%= form.label :password %>
    <%= form.password_field :password %>

    <%= form.label :password_confirmation, "Password Confirmation" %>
    <%= form.password_field :password_confirmation %>

    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to "#{user.username}", user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Username:</h3>
<%= @user.username %><br>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>